### ISSUE TITLE
Complete translation to spanish

### ISSUE THREAD

**Issue by jcl86** [Middlederg/new-celebrities#2]
Complete translation to spanish language

**Comment by Carababusha** [comment]
Kaixo @jcl86!

Do you need help with translating the project into Spanish? Give me a shout if you do, Translator here happy to help 😊

**Comment by jcl86** [comment]
Hello @Carababusha!

I have already started translating some texts, but this task is not yet finished, so it would be great if you want to continue with it.
The translation system in this project is based in editing .resx files. Specifically, the files that are in progress are:

`
src\NewCelebrities.Web\Pages\Play\Play.es.resx
`
`src\NewCelebrities.Web\Rounds\RoundTranslator.es.resx`

I use visual studio IDE to edit these files, but vs code, or anoter editor, would probably be suitable for this task too.

When you open the file, the second column ("Valor") is edited with the translated value.

![image](https://user-images.githubusercontent.com/18242071/194749993-9e2d395f-30e4-4f17-b272-8f8e4a038c61.png)

Thank you for your contribution offering, it would be great if you want to collaborate!

**Comment by Carababusha** [comment]
Brilliant! The texts that have already been translated will make great sources of reference to ensure the finished translation is consistent throughout. Ideally we should compile a glossary for consistency, but reference files are OK too. Which ones would you like me to translate, then?

**Comment by jcl86** [comment]
I didn't know that such a thing like a glossary was used in translation 😃 In fact, this is the first time i am adding multilanguage to an aplication, so I am exploring best way of doing

So if you want to start with these 2 files
`
src\NewCelebrities.Web\Pages\Play\Play.es.resx
`
`
src\NewCelebrities.Web\Rounds\RoundTranslator.es.resx
`
Probably it will be neccesary to add more literals to these files, or add another resource files, but for now we can begin with those 2

**Comment by Carababusha** [comment]
Sounds like a plan 👍

And yes, glossaries are used in translation to make sure the terminology is translated consistently throughout. Microsoft for example maintain a vast library of them in the languages their products are localised into. That way the terminology and entire strings can remain the same, regardless of the translators who may have to refer to it in further applications, etc.

But yeah, let's start with those two files for now 😄
